### ISSUE TITLE
Provide zipped QGS Project downlaod

### ISSUE THREAD

**Issue by lucernae** [ismailsunni/geonode_qgis_server#22]
It is sometimes useful to provide links to download as QGS Project zipped file

**Comment by gubuntu** [comment]
This is a duplicate of https://github.com/kartoza/geonode/issues/157. Also please be aware of going out of scope. This task is for sprint 2. Only work on it now if Etienne/Ismail need it for their QGIS client work. Otherwise leave till Sprint 2 and focus on Sprint 1 Issues that need to be complete by next Thursday.

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#182
